export const CITIES_INIT = 'CITIES_INIT';
export const SERVICES_INIT = 'SERVICES_INIT';
export const SEARCH_TEXT='SEARCH_TEXT'
export const CITY_CONTENT = 'CITY_CONTENT';
export const SERVICE_CONTENT = 'SERVICE_CONTENT';
export const LOAD_FAIL='LAOD_FAIL';
export const RESULT_MESSAGE='RESULT_MESSAGE';
export const LOAD_SERVICES_COMPANIES='LOAD_SERVICES_COMPANIES';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

export const LOAD_MOD_BUSINESS = 'LOAD_MOD_BUSINESS';
export const LOAD_MOD_FAIL = 'LOAD_MOD_FAIL';
export const CREATE_MOD_BUSINESS = 'CREATE_MOD_BUSINESS';
export const UPDATE_BUSINESS = 'UPDATE_BUSINESS';

export const LOAD_BUSINESS_SCHEDULE ='LOAD_BUSINESS_SCHEDULE';

export const ADMIN_LOAD_SERVICES= 'ADMIN_LOAD_SERVICES';
export const ADMIN_LOAD_ERROR= 'ADMIN_LOAD_ERROR';






